### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by tekdope** [TiBeN/ia-mame#12] opened 2018-05-25 21:31 UTC
I am having this message when I run IA-Mame.

java.lang.NoClassDefFoundError: javax/xml/bind/DataBindingException

Any solution or workaround?

**Comment by TiBeN** [comment] 2018-05-26 06:12
Hi, 
It seems to be related to issue #10. I'm planning a maintenance release to fix this among other things asap. 

Thanks for report.

**Comment by TiBeN** [comment] 2018-05-27 12:34
I confirm this issue is a duplicate of #10. I close this one. Please refers to #10. Thanks

**Closed as completed by TiBeN** 2018-05-27 12:34 UTC
